# Generated by Django 5.2.14 on 2026-05-26 08:54

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Angajator',
                'verbose_name_plural': 'Angajatori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Judet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'verbose_name': 'Județ',
                'verbose_name_plural': 'Județe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Posting URL — primary key from posturi.gov.ro', max_length=500, unique=True)),
                ('title', models.CharField(help_text='pozitie', max_length=500)),
                ('detalii_raw', models.TextField(blank=True, default='', help_text='detalii — comma-separated tags, kept verbatim')),
                ('published_at', models.DateField(blank=True, help_text='publicat_in', null=True)),
                ('expires_at', models.DateField(blank=True, help_text='expira_in', null=True)),
                ('url_judet', models.URLField(blank=True, default='', max_length=500)),
                ('tip', models.CharField(blank=True, default='', help_text='Listing type from index page', max_length=100)),
                ('updates_raw', models.TextField(blank=True, default='', help_text='updates — change log from scraper, parsed later')),
                ('job_level', models.CharField(blank=True, default='', help_text='Nivel — execuție / conducere', max_length=120)),
                ('job_type', models.CharField(blank=True, default='', help_text='Tip — Permanent / Temporar', max_length=120)),
                ('employer_category', models.CharField(blank=True, default='', max_length=200)),
                ('categorie', models.CharField(blank=True, default='', help_text='Funcție publică / contractuală', max_length=120)),
                ('announcement_url', models.URLField(blank=True, default='', help_text='Attachment URL (doc/pdf)', max_length=500)),
                ('body_markdown', models.TextField(blank=True, default='')),
                ('other_links', models.JSONField(blank=True, default=list)),
                ('nr_posturi', models.IntegerField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=40)),
                ('contact_email', models.CharField(blank=True, default='', max_length=200)),
                ('contact_person', models.CharField(blank=True, default='', max_length=200)),
                ('data_limita_depunere', models.DateTimeField(blank=True, null=True)),
                ('data_proba_scrisa', models.DateField(blank=True, null=True)),
                ('data_interviu', models.DateField(blank=True, null=True)),
                ('data_rezultate_finale', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateField(blank=True, help_text='Set by importer; can detect dropped postings', null=True)),
                ('inferred', models.JSONField(blank=True, default=dict, help_text='Reserved for v2/v3 derived fields')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='jobs.employer')),
                ('judet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='jobs.judet')),
            ],
            options={
                'verbose_name': 'Anunț',
                'verbose_name_plural': 'Anunțuri',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eveniment', models.CharField(max_length=500)),
                ('data', models.DateField()),
                ('ora', models.TimeField(blank=True, null=True)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='jobs.jobposting')),
            ],
            options={
                'verbose_name': 'Eveniment calendar',
                'verbose_name_plural': 'Calendar evenimente',
                'ordering': ['data', 'id'],
                'indexes': [models.Index(fields=['data', 'posting'], name='jobs_calend_data_1f71ac_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['expires_at'], name='jobs_jobpos_expires_f58cf5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['published_at'], name='jobs_jobpos_publish_c4adba_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['employer'], name='jobs_jobpos_employe_a620fa_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['judet'], name='jobs_jobpos_judet_i_81bb23_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='jobs_jobpos_search__a9892e_gin'),
        ),
    ]
