# Generated by Django 5.2.14 on 2026-05-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_romanian_unaccent_fts'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='attachment_text',
            field=models.TextField(blank=True, default='', help_text='Plain text extracted from downloaded attachment (docx/doc/pdf)'),
        ),
    ]
