# Generated by Django 5.2.14 on 2026-05-26 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobposting_attachment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=500, unique=True)),
                ('auto_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='jobs.employer')),
            ],
            options={
                'verbose_name': 'Alias angajator',
                'verbose_name_plural': 'Aliasuri angajatori',
                'ordering': ['alias_name'],
            },
        ),
    ]
