# Generated by Django 5.2.14 on 2026-05-26 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_employer_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateField()),
                ('fields_changed', models.CharField(help_text='Comma-separated field names that changed, or "New entry"', max_length=500)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_log', to='jobs.jobposting')),
            ],
            options={
                'verbose_name': 'Actualizare anunț',
                'verbose_name_plural': 'Actualizări anunțuri',
                'ordering': ['changed_at'],
                'constraints': [models.UniqueConstraint(fields=('posting', 'changed_at', 'fields_changed'), name='unique_posting_update')],
            },
        ),
    ]
