# Generated by Django 5.2.14 on 2026-06-08 21:58

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobpostingschemavariant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['job_level'], name='jobs_jobpos_job_lev_936a56_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=django.contrib.postgres.indexes.GinIndex(fields=['inferred'], name='jobs_jobpos_inferre_8dcf5b_gin'),
        ),
    ]
