# Generated by Django 5.2.14 on 2026-09-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_jobposting_jobs_jobpos_job_lev_936a56_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="judet_raw",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Source județ string kept verbatim when it could not be matched to a county (see apps.jobs.judete). Empty means the county resolved cleanly.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="locality",
            field=models.CharField(
                blank=True,
                default="",
                help_text="City/commune, split out of the source's 'LOCALITY, County' badge",
                max_length=160,
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["locality"], name="jobs_jobpos_localit_3e7d7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["judet_raw"], name="jobs_jobpos_judet_r_67af60_idx"
            ),
        ),
    ]
