# Generated by Django 5.2.14 on 2026-09-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_jobposting_judet_raw_jobposting_locality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="attachment_meta",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Per-file descriptors written by extract_attachments: [{url, ext, bytes, kind}]. `kind` is null for an ordinary announcement.",
            ),
        ),
    ]
