# Generated by Django 5.2.14 on 2026-09-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobposting_attachment_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='cancelled',
            field=models.BooleanField(default=False, help_text="Competition withdrawn: the index lists 'Anunț anulat' instead of an expiry date. Distinct from expired — the detail page still carries real dates, so without this flag a cancelled announcement reads as an open job."),
        ),
    ]
