# Generated by Django 5.2.14 on 2026-09-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_jobposting_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='salary_estimate',
            field=models.JSONField(blank=True, help_text='Gross monthly estimate from the draft salary grid, written by estimate-salaries.py. Derived, never scraped: postings almost never state a salary. Recomputable from occupation + context alone, so a new variant of the draft costs a script run, not a re-extraction.', null=True),
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_norm', models.CharField(help_text='ocupatii.parse_title(raw).base_norm — the dictionary key.', max_length=300, unique=True)),
                ('title_sample', models.CharField(blank=True, default='', help_text='One raw title that produced this key, for debugging.', max_length=300)),
                ('canonical', models.CharField(help_text="Display form, e.g. 'Asistent medical generalist'.", max_length=300)),
                ('cor_code', models.CharField(blank=True, db_index=True, default='', max_length=6)),
                ('cor_label', models.CharField(blank=True, default='', max_length=300)),
                ('isco_group', models.CharField(blank=True, db_index=True, default='', help_text='ISCO-08 unit group, always cor_code[:4]. Derived, never asked of a model.', max_length=4)),
                ('grid_selector', models.JSONField(blank=True, default=dict, help_text='Which row of the draft grid this occupation is paid on {anexa, cod, functie_grila, regim, tip_post, nivel_administrativ}. A selector, not a salary: the law is an unadopted draft, so pay is recomputed from here whenever the variant changes.')),
                ('study_level', models.CharField(blank=True, default='', max_length=20)),
                ('match_confidence', models.CharField(default='incert', help_text='exact | probabil | incert | none — how sure the mapping is.', max_length=12)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('grid_version', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ocupație',
                'verbose_name_plural': 'Ocupații',
                'ordering': ['canonical'],
                'indexes': [models.Index(fields=['match_confidence'], name='jobs_occupa_match_c_6697cf_idx'), models.Index(fields=['canonical'], name='jobs_occupa_canonic_3f11fe_idx')],
            },
        ),
        migrations.AddField(
            model_name='jobposting',
            name='occupation',
            field=models.ForeignKey(blank=True, help_text='Normalised occupation, resolved from the title by normalize-titles.py.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postings', to='jobs.occupation'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['occupation'], name='jobs_jobpos_occupat_9f538d_idx'),
        ),
    ]
