# Generated by Django 5.2.14 on 2026-10-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_jobposting_salary_estimate_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='detail_content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 of the extracted detail content — the source revision identity. Enrichment results are only current while they match this hash.', max_length=64),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='detail_fetched_at',
            field=models.DateTimeField(blank=True, help_text='When the cached detail page was last successfully retrieved from the source.', null=True),
        ),
    ]
