# Generated by Django 5.2.14 on 2026-10-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_jobposting_detail_content_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='schema_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='schema_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='schema_prompt_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='schema_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='schema_source_revision',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobpostingschemavariant',
            name='source_revision',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
