# Generated by Django 5.2.14 on 2026-10-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_jobposting_schema_extracted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
